version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    expose:
      - "2181" 
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    expose:
      - "9092" 
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  fynd:
    container_name: fynd
    image: praveenraturi/fynd:v1
    depends_on:
      - kafka
    expose:
      - "6001" 
    ports:
      - "6001:8080"
    environment:
      - BOOTSTRAP_URL=kafka:9092
      - FILE_PATH=/opt/
    volumes:
      - .:/opt/