version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    expose:
      - 2181
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT= 2181
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME= kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0-beta1
    ports:
      - "8082:8081"
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    environment:
      - SCHEMA_REGISTRY_HOST_NAME= schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS= PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT= 300

  kafka-connect:
    image: praveenraturi/praveencustomconnector:v2
    container_name: kafka-connect
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    expose:
      - "8083"
    ports:
      - "8083:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS= kafka:9092
      - CONNECT_REST_ADVERTISED_HOST_NAME= kafka-connect
      - CONNECT_REST_PORT= 8083
      - CONNECT_GROUP_ID= compose-connect-group
      - CONNECT_CONFIG_STORAGE_TOPIC= docker-connect-configs
      - CONNECT_OFFSET_STORAGE_TOPIC= docker-connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC= docker-connect-status
      - CONNECT_KEY_CONVERTER= org.apache.kafka.connect.storage.StringConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL= "http://schema-registry:8082"
      - CONNECT_VALUE_CONVERTER= org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL= "http://schema-registry:8082"
      - CONNECT_INTERNAL_KEY_CONVERTER= org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER= org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_ENABLE= false
      - CONNECT_VALUE_CONVERTER_SCHEMA_ENABLE= false
      - CONNECT_LOG4J_ROOT_LOGLEVEL= "ERROR"
      - CONNECT_LOG4J_LOGGERS= "org.reflections=ERROR,com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue=ERROR"
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR= 1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR= 1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR= 1
      - CONNECT_PLUGIN_PATH= "/usr/share/java,/usr/share/confluent-hub-components/"
      - CONNECT_CONFIG_PROVIDERS= "file"